name: posegal
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  curved_navigation_bar: ^0.3.1
  after_layout: ^1.0.7+2
  graphql_flutter: ^2.1.0
  # cloud_firestore: ^0.12.9+4
  # firebase_core: ^0.4.0+9
  # firebase_analytics: ^5.0.2
  # firebase_auth: ^0.14.0+5
  flutter_svg: ^0.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/players/
    - assets/games/
    - assets/shops/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Bold.ttf
          weight: 700
        - asset: assets/fonts/Oxygen-Light.ttf
          weight: 400
        - asset: assets/fonts/Oxygen-Regular.ttf
          weight: 300
